### ISSUE TITLE
有问题想咨询一下，方便留个联系方式吗

### ISSUE THREAD

**Issue by ghost** [TiyaAnlite/xybAutoSign#1]

**Comment by TiyaAnlite** [comment]
如果是关于本项目的咨询，可以直接在本issues下提出

**Comment by mlzxc** [comment]
> 如果是关于本项目的咨询，可以直接在本issues下提出

配置好了触发函数后仍然这样，中间不知道为什么就成功了一次，其他的均显示以下结果
ERROR RequestId:cb3c5e69-bc0b-4e3d-89c8-707efa1df747 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 12, in main_handler\n    raise RuntimeError(\"触发器配置不正确，请参考配置说明\")\nRuntimeError: 触发器配置不正确，请参考配置说明","statusCode":430}

**Comment by TiyaAnlite** [comment]
> 

触发器名称是有要求的，工具利用触发器名称来确定签到还是签出，触发器名称必须设置且为`SignOut`或`SignIn`的其中一个，区分大小写。检查你的触发器名是否正确，可以尝试使用代码编辑下的调试功能，手动选择触发器类型事件构造请求进行调试

**Comment by TiyaAnlite** [comment]
> > 如果是关于本项目的咨询，可以直接在本issues下提出
> 
> 配置好了触发函数后仍然这样，中间不知道为什么就成功了一次，其他的均显示以下结果 ERROR RequestId:cb3c5e69-bc0b-4e3d-89c8-707efa1df747 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n File "/var/user/index.py", line 12, in main_handler\n raise RuntimeError("触发器配置不正确，请参考配置说明")\nRuntimeError: 触发器配置不正确，请参考配置说明","statusCode":430}

触发器名称是有要求的，工具利用触发器名称来确定签到还是签出，触发器名称必须设置且为`SignOut`或`SignIn`的其中一个，区分大小写。检查你的触发器名是否正确，可以尝试使用代码编辑下的调试功能，手动选择触发器类型事件构造请求进行调试

**Comment by mlzxc** [comment]
就是我有时候需要手动签到，触发器配置好后只能在【未来的时间点】签到，比如我触发设置的是每天早上9点，但是因为服务器或者某些原因，9点没有签到成功，我需要手动的签到，这时候我想点【测试】来进行签到应该怎么编辑您说的【调试功能】来手动选择触发器类型

> > > 如果是关于本项目的咨询，可以直接在本issues下提出
> > 
> > 
> > 配置好了触发函数后仍然这样，中间不知道为什么就成功了一次，其他的均显示以下结果 ERROR RequestId:cb3c5e69-bc0b-4e3d-89c8-707efa1df747 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n File "/var/user/index.py", line 12, in main_handler\n raise RuntimeError("触发器配置不正确，请参考配置说明")\nRuntimeError: 触发器配置不正确，请参考配置说明","statusCode":430}
> 
> 触发器名称是有要求的，工具利用触发器名称来确定签到还是签出，触发器名称必须设置且为`SignOut`或`SignIn`的其中一个，区分大小写。检查你的触发器名是否正确，可以尝试使用代码编辑下的调试功能，手动选择触发器类型事件构造请求进行调试

**Comment by TiyaAnlite** [comment]
> 就是我有时候需要手动签到，触发器配置好后只能在【未来的时间点】签到，比如我触发设置的是每天早上9点，但是因为服务器或者某些原因，9点没有签到成功，我需要手动的签到，这时候我想点【测试】来进行签到应该怎么编辑您说的【调试功能】来手动选择触发器类型
> 
> > > > 如果是关于本项目的咨询，可以直接在本issues下提出
> > > 
> > > 
> > > 配置好了触发函数后仍然这样，中间不知道为什么就成功了一次，其他的均显示以下结果 ERROR RequestId:cb3c5e69-bc0b-4e3d-89c8-707efa1df747 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n File "/var/user/index.py", line 12, in main_handler\n raise RuntimeError("触发器配置不正确，请参考配置说明")\nRuntimeError: 触发器配置不正确，请参考配置说明","statusCode":430}
> > 
> > 
> > 触发器名称是有要求的，工具利用触发器名称来确定签到还是签出，触发器名称必须设置且为`SignOut`或`SignIn`的其中一个，区分大小写。检查你的触发器名是否正确，可以尝试使用代码编辑下的调试功能，手动选择触发器类型事件构造请求进行调试

在函数编辑下进入函数代码标签页，往下拉找到测试板块，测试事件选择Timer定时触发器模板，TriggerName修改对应的触发器名称即可，点击部署按钮旁的测试按钮就能运行
![截图](https://user-images.githubusercontent.com/28893152/160268281-db71bb9a-c300-47f6-a1d7-adbf646bf77e.jpg)

**Comment by mlzxc** [comment]
> 

懂了，感谢！

**Comment by mlzxc** [comment]
> > 就是我有时候需要手动签到，触发器配置好后只能在【未来的时间点】签到，比如我触发设置的是每天早上9点，但是因为服务器或者某些原因，9点没有签到成功，我需要手动的签到，这时候我想点【测试】来进行签到应该怎么编辑您说的【调试功能】来手动选择触发器类型
> > > > > 如果是关于本项目的咨询，可以直接在本issues下提出
> > > > 
> > > > 
> > > > 配置好了触发函数后仍然这样，中间不知道为什么就成功了一次，其他的均显示以下结果 ERROR RequestId:cb3c5e69-bc0b-4e3d-89c8-707efa1df747 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n File "/var/user/index.py", line 12, in main_handler\n raise RuntimeError("触发器配置不正确，请参考配置说明")\nRuntimeError: 触发器配置不正确，请参考配置说明","statusCode":430}
> > > 
> > > 
> > > 触发器名称是有要求的，工具利用触发器名称来确定签到还是签出，触发器名称必须设置且为`SignOut`或`SignIn`的其中一个，区分大小写。检查你的触发器名是否正确，可以尝试使用代码编辑下的调试功能，手动选择触发器类型事件构造请求进行调试
> 
> 在函数编辑下进入函数代码标签页，往下拉找到测试板块，测试事件选择Timer定时触发器模板，TriggerName修改对应的触发器名称即可，点击部署按钮旁的测试按钮就能运行 ![截图](https://user-images.githubusercontent.com/28893152/160268281-db71bb9a-c300-47f6-a1d7-adbf646bf77e.jpg)

现在有种情况是，学校集中实习的，签到界面没有签到地址的，就是签哪里都会显示正常签到，但是用项目提交没办法签到成功，
![image](https://user-images.githubusercontent.com/64181905/160268584-ba444f4a-95e0-4a8b-9037-3525c792f546.png)

**Comment by TiyaAnlite** [comment]
集中实习的这种情况之前没有遇到过，所以不清楚这种情况下的签到流程是怎么样的，目前来说暂时无法做适配

**Comment by ghost** [comment]
我能提供材料，并且我已经分析到大概的原因，抓包了解了一下，跟另一位作者研究好了，他用的jave写的，功能已经可以实现，但是他没办法使用Python写出来，您能帮忙完善一下吗，可以提供一点捐赠

**Comment by TiyaAnlite** [comment]
> 我能提供材料，并且我已经分析到大概的原因，抓包了解了一下，跟另一位作者研究好了，他用的jave写的，功能已经可以实现，但是他没办法使用Python写出来，您能帮忙完善一下吗，可以提供一点捐赠

可以的，我会尽自己能力范围尽可能提供帮助

**Comment by mlzxc** [comment]
QQ204744375
