### ISSUE TITLE
关于logger的smtp推送

### ISSUE THREAD

**Issue by wdssfff00** [TiyaAnlite/xybAutoSign#11]
如题，大佬脚本还是可以正常签到的，不过因为没有推送提醒咱害怕哪天突然抽风失效导致错过签到，＞﹏＜

def init_logger(logger: logging.Logger, fmt="%(asctime)s - %(name)s - %(levelname)s: %(message)s", encoding='utf-8'):
    # logger.setLevel(logging.INFO)
    formatter = logging.Formatter(fmt)
    
    sh = logging.StreamHandler()  ## 定义一个控制台，在控制台上将对应的信息来进行输出
    sh.setFormatter(formatter)   ## 来设置出相应的过滤输出的格式的
    
    handler = logging.FileHandler("log.txt")  ## 这里是来定义的一个日志文件
    handler.setFormatter(formatter)  ## 然后是日志文件里面对应的所输出的格式

    logger.addHandler(sh)
    logger.addHandler(handler)

这里我这么写倒是实现了输出log到txt，但百度logger的smtp推送无果。。。
想咨询下大佬怎么写才能实现smtp或者plush或者方糖，企业微信之类的推送

**Comment by TiyaAnlite** [comment]
- 写文件日志的话建议用`TimedRotatingFileHandler`，不然缺乏维护很快就会写爆的
- 推送这个项目原先是没有集成的推送的，但提供了完善的Webhooks可供接入外部功能
- 最近有人PR新增了并完善本地运行的适配，并提供了一些推送功能，不过合并的话近期比较忙需要一些时间
- 文档已经指出了Webhooks的数据格式，就是一个普通的dict字典，因此主要用自己熟悉的py编程方式就能实现
- 最后关于smtp。很多邮件提供商已经对smtp管控较为严格了，用于频繁或者稳定地进行邮件发送难以保证，建议还是考虑用其他的推送平台实现，关于你提到的几种途径，据我了解的是企业微信最方便，企业微信的群机器人只要一个webhooks地址就可以推了

**Comment by wdssfff00** [comment]
哦哦，Webhooks我一会搞搞，我看到有人pr了，刚才试了下一直有报错，好像是没传入配置文件？？


2022-09-20 23:23:37,260 - XybSign - ERROR: 载入账户时出现异常
2022-09-20 23:23:37,260 - XybSign - ERROR: type object argument after ** must be a mapping, not str
Traceback (most recent call last):
  File "xyb.py", line 435, in __init__
    self._accounts.append(XybAccount(**acc))
TypeError: type object argument after ** must be a mapping, not str
2022-09-20 23:23:37,262 - XybSign - ERROR: 载入账户时出现异常
2022-09-20 23:23:37,262 - XybSign - ERROR: type object argument after ** must be a mapping, not str
Traceback (most recent call last):
  File "xyb.py", line 435, in __init__
    self._accounts.append(XybAccount(**acc))
TypeError: type object argument after ** must be a mapping, not str
2022-09-20 23:23:37,263 - XybSign - INFO: 已载入 0 个账号
2022-09-20 23:23:37,263 - XybSign - INFO: 开始批量签到 0 个账户
2022-09-20 23:23:37,263 - XybSign - INFO: 任务结束，0(成功) / 0(失败)
2022-09-20 23:23:37,264 - XybSign - INFO: Webhooks: 0 || 0(完成) / 0(失败)

**Comment by TiyaAnlite** [comment]
> 哦哦，Webhooks我一会搞搞，我看到有人pr了，刚才试了下一直有报错，好像是没传入配置文件？？
> 
> 2022-09-20 23:23:37,260 - XybSign - ERROR: 载入账户时出现异常 2022-09-20 23:23:37,260 - XybSign - ERROR: type object argument after ** must be a mapping, not str Traceback (most recent call last): File "xyb.py", line 435, in **init** self._accounts.append(XybAccount(**acc)) TypeError: type object argument after ** must be a mapping, not str 2022-09-20 23:23:37,262 - XybSign - ERROR: 载入账户时出现异常 2022-09-20 23:23:37,262 - XybSign - ERROR: type object argument after ** must be a mapping, not str Traceback (most recent call last): File "xyb.py", line 435, in **init** self._accounts.append(XybAccount(**acc)) TypeError: type object argument after ** must be a mapping, not str 2022-09-20 23:23:37,263 - XybSign - INFO: 已载入 0 个账号 2022-09-20 23:23:37,263 - XybSign - INFO: 开始批量签到 0 个账户 2022-09-20 23:23:37,263 - XybSign - INFO: 任务结束，0(成功) / 0(失败) 2022-09-20 23:23:37,264 - XybSign - INFO: Webhooks: 0 || 0(完成) / 0(失败)

这个是配置文件有问题，检查格式是否规范

**Comment by wdssfff00** [comment]
> > 哦哦，Webhooks我一会搞搞，我看到有人pr了，刚才试了下一直有报错，好像是没传入配置文件？？
> > 2022-09-20 23：23：37，260 - XybSign - 错误： 载入账户时出现异常 2022-09-20 23：23：37，260 - XybSign - 错误：后面的类型对象参数 ** 必须是  映射，而不是 str 跟踪回（最近调用最后）： 文件“xyb.py”，第 435 行，**初始化**self._accounts.append（XybAccount（**acc）） 类型错误： 键入对象参数之后的 ** 必须是  映射，而不是 str 2022-09-20 23：23：37，262 - XybSign - 错误： 载入账户时出现异常 2022-09-20 23：23：37，262 - XybSign - 错误：后面的类型对象参数 **  必须是映射，而不是 str 回溯（最近调用最后）： 文件“xyb.py”，第 435 行，**初始化** self._accounts.append（XybAccount（**acc）） 类型错误：键入对象参数之后 ** 必须是  映射，not str 2022-09-20 23：23：37，263 - XybSign - 信息： 已载入 0 个账号 2022-09-20 23：23：37，263 - XybSign - 信息： 开始批量签到 0 个账户 2022-09-20 23：23：37，263 - XybSign - 信息： 任务结束，0（成功） / 0（失败） 2022-09-20 23：23：37，264 - XybSign - 信息： Webhooks： 0 ||0(完成) / 0(失败)
> 
> 这个是配置文件有问题，检查格式是否规范

json格式没问题，但就是报错，用您的accounts.json内容就没事，似乎。。。好像。。。。pr的xyb.py需要改一下读取配置那部分代码
