### ISSUE TITLE
请问大佬有办法实现延时触发吗

### ISSUE THREAD

**Issue by RenOrimaki** [TiyaAnlite/xybAutoSign#13]
可以延迟程序签到时间，在一个时间段内随机延迟一段时间进行签到，避免过于准时吗

**Comment by TiyaAnlite** [comment]
> 可以延迟程序签到时间，在一个时间段内随机延迟一段时间进行签到，避免过于准时吗

这个内容早在设计之初就考虑过，但是由于目前是云函数的执行环境下，由于批量签到，引入大量的随机延迟极有可能会导致函数运行超时等不可控因素，因此在批量签到版中并没有引入内置随机延迟的支持。随机延迟可以通过API外部调用方式，自行控制调度时机来实现

**Comment by RenOrimaki** [comment]
请问如果非批量签到，只有一个账号的情况下能否通过运行程序时可以加入int参数，延迟程序签到时间，如autoSign.py 1800将在0-1800（秒）内随机延迟一段时间进行签到呢？

**Comment by TiyaAnlite** [comment]
> 请问如果非批量签到，只有一个账号的情况下能否通过运行程序时可以加入int参数，延迟程序签到时间，如autoSign.py 1800将在0-1800（秒）内随机延迟一段时间进行签到呢？

这个以后可能会考虑，不过应该不会这么快

**Comment by RenOrimaki** [comment]
> > 请问如果非批量签到，只有一个账号的情况下能否通过运行程序时可以加入int参数，延迟程序签到时间，如autoSign.py 1800将在0-1800（秒）内随机延迟一段时间进行签到呢？
> 
> 
> 
> 这个以后可能会考虑，不过应该不会这么快

好的，非常感谢
