### ISSUE TITLE
如果没有集中实习自主实习就需要填经纬度吧  作者大大

### ISSUE THREAD

**Issue by XCQINzs** [TiyaAnlite/xybAutoSign#15]

**Comment by TiyaAnlite** [comment]
经纬度对于实习的类型来说是独立的，这个取决于你的学校在配置这个实习的时候对签到位置有没有要求，自主实习也可能需要有定位的，建议以具体的实习信息为准。（另外一提因为项目年久没有维护，不保证一定能用）

**Comment by XCQINzs** [comment]
方便加个q嘛



---原始邮件---
发件人: "Tiya ***@***.***&gt;
发送时间: 2023年10月25日(周三) 晚上9:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TiyaAnlite/xybAutoSign] 如果没有集中实习自主实习就需要填经纬度吧  作者大大 (Issue #15)




 
经纬度对于实习的类型来说是独立的，这个取决于你的学校在配置这个实习的时候对签到位置有没有要求，自主实习也可能需要有定位的，建议以具体的实习信息为准。（另外一提因为项目年久没有维护，不保证一定能用）

**Comment by XCQINzs** [comment]
不懂的还可以请教你



---原始邮件---
发件人: "Tiya ***@***.***&gt;
发送时间: 2023年10月25日(周三) 晚上9:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TiyaAnlite/xybAutoSign] 如果没有集中实习自主实习就需要填经纬度吧  作者大大 (Issue #15)




 
经纬度对于实习的类型来说是独立的，这个取决于你的学校在配置这个实习的时候对签到位置有没有要求，自主实习也可能需要有定位的，建议以具体的实习信息为准。（另外一提因为项目年久没有维护，不保证一定能用）

**Comment by TiyaAnlite** [comment]
如果希望继续的话可以用邮箱，比较少上q

**Comment by XCQINzs** [comment]
那v行不。我有个代码得修一下



---原始邮件---
发件人: "Tiya ***@***.***&gt;
发送时间: 2023年10月25日(周三) 晚上11:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TiyaAnlite/xybAutoSign] 如果没有集中实习自主实习就需要填经纬度吧  作者大大 (Issue #15)




 
如果希望继续的话可以用邮箱，比较少上q

**Comment by XCQINzs** [comment]
好像能签 但是后台会异常

**Comment by TiyaAnlite** [comment]
如果有异常的话可以吧输出贴到这里，不过因为比较忙不一定能解决

**Comment by XCQINzs** [comment]
是可以签到成功，校友邦后台提示异常，跟外勤不一样



---原始邮件---
发件人: "Tiya ***@***.***&gt;
发送时间: 2023年10月26日(周四) 凌晨0:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TiyaAnlite/xybAutoSign] 如果没有集中实习自主实习就需要填经纬度吧  作者大大 (Issue #15)




 
如果有异常的话可以吧输出贴到这里，不过因为比较忙不一定能解决

**Comment by XCQINzs** [comment]
是可以签到成功，校友邦后台提示异常，跟外勤不一样,是校友邦加了效验？

**Comment by XCQINzs** [comment]
今天校友邦更新了个备注签到。



---原始邮件---
发件人: "Tiya ***@***.***&gt;
发送时间: 2023年10月26日(周四) 凌晨0:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TiyaAnlite/xybAutoSign] 如果没有集中实习自主实习就需要填经纬度吧  作者大大 (Issue #15)




 
如果有异常的话可以吧输出贴到这里，不过因为比较忙不一定能解决

**Comment by XCQINzs** [comment]
---原始邮件---
发件人: "Tiya ***@***.***&gt;
发送时间: 2023年10月26日(周四) 凌晨0:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TiyaAnlite/xybAutoSign] 如果没有集中实习自主实习就需要填经纬度吧  作者大大 (Issue #15)




 
如果有异常的话可以吧输出贴到这里，不过因为比较忙不一定能解决

**Comment by TiyaAnlite** [comment]
可能是近一年对签到添加了一些验证，去年对请求加验证的时候逆向就花了不少精力，当前相较于之前资源和手段更加匮乏，目前这个项目也已经停止维护，恕无法提供更多支持

**Comment by XCQINzs** [comment]
他今天刚更新的，昨天还能签到成功。



---原始邮件---
发件人: "Tiya ***@***.***&gt;
发送时间: 2023年10月26日(周四) 中午11:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TiyaAnlite/xybAutoSign] 如果没有集中实习自主实习就需要填经纬度吧  作者大大 (Issue #15)




 
可能是近一年对签到添加了一些验证，去年对请求加验证的时候逆向就花了不少精力，当前相较于之前资源和手段更加匮乏，目前这个项目也已经停止维护，恕无法提供更多支持

**Comment by XCQINzs** [comment]
有偿解决一手。



---原始邮件---
发件人: "Tiya ***@***.***&gt;
发送时间: 2023年10月26日(周四) 中午11:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TiyaAnlite/xybAutoSign] 如果没有集中实习自主实习就需要填经纬度吧  作者大大 (Issue #15)




 
可能是近一年对签到添加了一些验证，去年对请求加验证的时候逆向就花了不少精力，当前相较于之前资源和手段更加匮乏，目前这个项目也已经停止维护，恕无法提供更多支持

**Comment by TiyaAnlite** [comment]
抱歉，本职工作较忙，恕不能回应请求
