### ISSUE TITLE
我的人比较多 签到签退都不行，几十个人把最后那个打上了 其他的都没打上 测试成功的

### ISSUE THREAD

**Issue by muzisunqi123** [TiyaAnlite/xybAutoSign#3]
![微信图片_20220408124310](https://user-images.githubusercontent.com/99589734/162365331-94f4ffab-7d4d-4c9a-bed8-41dc33e0a537.png)
请帮忙看一下

**Comment by TiyaAnlite** [comment]
> ![微信图片_20220408124310](https://user-images.githubusercontent.com/99589734/162365331-94f4ffab-7d4d-4c9a-bed8-41dc33e0a537.png) 请帮忙看一下

日志不完整，无法看到所有输出

**Comment by TiyaAnlite** [comment]
> > ![微信图片_20220408124310](https://user-images.githubusercontent.com/99589734/162365331-94f4ffab-7d4d-4c9a-bed8-41dc33e0a537.png) 请帮忙看一下
> 
> 日志不完整，无法看到所有输出

问题应该已经修复，拉取最新修改看看
