### ISSUE TITLE
请问楼主 现在有办法直接跳过健康码上传直接签到吗

### ISSUE THREAD

**Issue by muzisunqi123** [TiyaAnlite/xybAutoSign#6]

**Comment by muzisunqi123** [comment]
请问 现在有办法跳过健康码上传直接签到吗

**Comment by TiyaAnlite** [comment]
目前也有收到过一些反馈提示需要先上传健康码才能签到，这种情况只能按照正规流程进行签到。后续**没有**添加跳过健康码签到的计划。

**Comment by PilyziFox** [comment]
> 目前也有收到过一些反馈提示需要先上传健康码才能签到，这种情况只能按照正规流程进行签到。后续**没有**添加跳过健康码签到的计划。

冒昧的请问一下，没有更新计划是出于法律方面的顾虑吗？

**Comment by TiyaAnlite** [comment]
> > 目前也有收到过一些反馈提示需要先上传健康码才能签到，这种情况只能按照正规流程进行签到。后续**没有**添加跳过健康码签到的计划。
> 
> 冒昧的请问一下，没有更新计划是出于法律方面的顾虑吗？

跳过健康码签到的方式目前技术不可行，而且跳过健康码也是有风险的
