### ISSUE TITLE
什么 时候可以更新健康码行程码上传呢

### ISSUE THREAD

**Issue by muzisunqi123** [TiyaAnlite/xybAutoSign#8]
还有一个问题  签到时间间隔时间长一点在哪里设置呢  每天签到时间都紧紧挨着  老师问起来很难受

**Comment by muzisunqi123** [comment]
我现在触发器签到好了之后 不知道为啥还会触发一次签到 本签到位置正常 然后又自己触发了一次 位置就显示异常了 但是日志里面看不到 自动触发运行日志

**Comment by TiyaAnlite** [comment]
签到时间间隔变化无法用自动触发器方式实现，只能自己用服务器调API方式实现
最近准备毕业答辩，事比较多，应该一段时间内都没有时间继续更新功能
